name: mccontrol
version: '1.0'
main: org.hegglandtech.mccontrol.Mccontrol
api-version: '1.21'

permissions:
  mccontrol.admin:
    description: Allows the player to use all commands.
    default: op

commands:
  caninteractwithblocks:
    description: Grants the block placement permission to a player.
    usage: /mccontrol caninteractwithblocks <player> <true/false>
    permission: mccontrol.admin
  getmemory:
    description: Get the memory
    usage: /mccontrol getmemory
    permission: mccontrol.admin