name: mccontrol
version: '1.1'
main: org.hegglandtech.mccontrol.Mccontrol
api-version: '1.21'

permissions:
  mccontrol.admin:
    description: Allows the player to use all commands.
    default: op

commands:
  permission:
    description: Grants the block placement permission to a player.
    usage: permission <canBuild|canPvp> grant|revoke playername
    permission: mccontrol.admin
  modify:
    description: Modify a player permission
    usage: modify <permission> grant|revoke playeruuid
    permission: mccontrol.admin
  getmemory:
    description: Get the memory
    usage: getmemory
    permission: mccontrol.admin